// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wkcfpeurietbcbklcwxc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndrY2ZwZXVyaWV0YmNia2xjd3hjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2NjY5NjYsImV4cCI6MjA2ODI0Mjk2Nn0.R1_yhId_51Trxn2mKtL1aLt2TP6wcU6AfQ_2XYjRVu4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: false,
    flowType: 'pkce'
  }
});